what a difficult task!
X3ZvaWQ/a-simple-practice-gogogo-2 pull request #3
Opened 2020-01-28 10:16 UTC by conquer-eden

2020-01-29 05:47 UTC, x3zvawq requested changes
不要随意放弃啊...
明明很简单的说，你这个续期也太简单了吧而且，而且不要随便改别人的代码啊
新建一个action或者Controller写自己的
传值可以用postman传。算了 QQ说

2020-01-29 09:43 UTC, conquer-eden commented
爱你三千遍

2020-01-30 06:24 UTC, x3zvawq reviewed
干得漂亮
但是你是不是不记得我跟你说的
框架里面可以用$request->xxx 来获取传的值了
php可以用$_POST 但是用什么框架就应该遵循什么规范
对了 一般控制器起名规范是大驼峰
比如ApiController
这就是为什么我会说感觉apIIIController有些奇怪

2020-01-30 06:25 UTC, X3ZvaWQ commented
一个控制器可以写多个方法的，你可以把你的方法就加在ApiController下面，或者make一个控制器

2020-01-30 12:30 UTC, x3zvawq approved these changes
so good

2020-01-30 12:31 UTC, merged